### PR TITLE
Enable authorization for the advanced search

### PR DESCRIPTION
**Pull request by wooleyHeadspring**
Added authorization to advanced search to match existing controllers.

### CODE REVIEW

**Review by YogirajA — COMMENTED** [review]
@wooleyHeadspring This probably requires a small frontend change as well. We should just hide the Advanced Search link for non-Admin users to avoid the confusion.

**Review by YogirajA — CHANGES_REQUESTED** [review]
@wooleyHeadspring This probably requires a small frontend change as well. We should just hide the Advanced Search link for non-Admin users to avoid the confusion.

**Comment by wooleyHeadspring** [comment]
> @wooleyHeadspring This probably requires a small frontend change as well. We should just hide the Advanced Search link for non-Admin users to avoid the confusion.

@YogirajA I could do this change in #31 as it is part of the UI.

**Review by YogirajA — APPROVED** [review]

**Comment by YogirajA** [comment]
> > @wooleyHeadspring This probably requires a small frontend change as well. We should just hide the Advanced Search link for non-Admin users to avoid the confusion.
> 
> @YogirajA I could do this change in #31 as it is part of the UI.

Sounds good

**Pull request merged**
